#!/bin/bash
set -euo pipefail

readonly results_dir="$1"
readonly consensus_dir="$2"
readonly implementation_dir="$3"
readonly implementation="$(basename "$implementation_dir")"

. src/shared.sh

all_queries() {
    find ./queries -type d -maxdepth 1 -mindepth 1 -print0 | xargs -0 -n1 basename | sort
}

unwrap_scalar_if_needed() {
    local query="$1"

    if [[ -f "./implementations/${implementation}/SINGLE_POSSIBLE_MATCH_RETURNED_AS_SCALAR" && -f "./queries/${query}/SCALAR_RESULT" ]]; then
        ./src/unwrap_scalar.py
    else
        cat
    fi
}

implementation_status() {
    local query="$1"
    local matching_implementations="${consensus_dir}/${query}"

    if is_query_result_ok "${results_dir}/${query}/${implementation}"; then
        if [[ -s "$matching_implementations" ]]; then
            if grep "^${implementation}\$" < "$matching_implementations" > /dev/null; then
                echo "pass"
            else
                echo "fail"
            fi
        else
            echo "open"
        fi
    else
        echo "error"
    fi
}

query_entry() {
    local query="$1"
    local status
    status="$(implementation_status "$query")"

    if [[ "$status" != "pass" ]]; then
        echo "  - id: ${query}"
        echo "    status: ${status}"
        if [[ "$status" != "error" ]]; then
            echo -n "    result: "
            query_result_payload "${results_dir}/${query}/${implementation}" | unwrap_scalar_if_needed "$query" | ./src/oneliner_json.py
        fi
    fi
}

main() {
    local query

    echo "# This file was generated by src/compile_implementation_report.sh from https://github.com/cburgmer/json-path-comparison/"
    echo
    echo "# This file tracks all results of the given implementation for queries which the implementation either does not match"
    echo "# an existing consensus or where no consensus exists."
    echo "# It can be used to track changes in the underlying implementation and complements the regression report."
    echo

    echo "implementation: ${implementation}"

    echo "queries:"
    while IFS= read -r query; do
        query_entry "$query"
    done <<< "$(all_queries)"
}

main
